FROM golang:latest

LABEL maintainer="Shikhar Kannoje <shikharkannoje09@gmail.com>"

WORKDIR /app/APIGateway

COPY go.mod .

COPY go.sum .

RUN go mod download

COPY . .

ENV CACHE_DOMAIN 0.0.0.0:9000
ENV API_GATE_SERVER 0.0.0.0:9080
ENV DS_HOSTPORT 5432
ENV DS_HOSTNAME localhost
ENV DS_USERNAME postgres
ENV DS_PASSWORD root
ENV DS_DATABASE employee
ENV DS_SERVERRUN 0.0.0.0:9000 

RUN go build

EXPOSE 9080

CMD ["go", "run", "main.go"]
